version: 2
jobs:
  build:
    docker:
    - image: circleci/python:2.7.14
    steps:
    - checkout
    - run:
        name: install c7n
        command: pip install --user c7n==0.8.44.2
    - run:
        name: custodian version
        command: ~/.local/bin/custodian version
    - run:
        name: validate policies
        command: |
          cd ~/project/policies
          ls *.yml | xargs -n1 -P 4 ~/.local/bin/custodian validate
workflows:
  version: 2
  workflow:
    jobs:
    - build
