version: 2
jobs:
  build:
    docker:
    - image: circleci/python:2.7.14
    steps:
    - checkout
    - restore_cache:
        keys:
         - c7n-{{ .Branch }}-{{ checksum "package.json" }}
         - c7n-{{ .Branch }}-
         - c7n-
    - run:
        name: install c7n
        command: |
          pipenv install c7n==0.8.44.2
    - save_cache:
        key: c7n-{{ .Branch }}-{{ checksum "package.json" }}
        paths:
          - "~/.cache/pip"
          - "~/.local"
    - run:
        name: custodian version
        command: pipenv run custodian version
    - run:
        name: validate policies
        command: |
          cd ~/project/policies
          ls *.yml | xargs -n1 -P 4 pipenv run custodian validate
workflows:
  version: 2
  workflow:
    jobs:
    - build
